language: python
python:
  - 3.6

install:
  - pip3 install -r requirements.txt
  - pip3 install python3-coveralls
  - pip3 install coverage

script:
  - python3 -m pytest --cov

after_success:
  - coveralls
